### ISSUE TITLE
You have credentials committed into the repository

### ISSUE THREAD

**Issue by josh-stableprice** [Blindrabit/staffing_app_v2#1]
I don't know if this project is in use anywhere, but I thought I should highlight this for your attention 

Credential location: https://github.com/Blindrabit/staffing_app_v2/blob/2bb27115839eaba4d267cfb6b97a2304aab8a71f/shifts/scrape.py#L15

How to remove them: https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by Blindrabit** [comment]
Thank you for highlighting this.

I have removed these from past commits and have added as a secret environmental variable.
